/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */

export interface AssetInfo {
  aclass?: string;
  altname?: string;
  decimals?: number;
  display_decimals?: number;
  status?: string;
  margin_rate?: string;
  collateral_value?: number;
}
