/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */
import type { MarketSnapshot } from './marketSnapshot';
import type { PortfolioSummary } from './portfolioSummary';
import type { PriceAlert } from './priceAlert';
import type { PromptRecord } from './promptRecord';
import type { SubscriptionHealth } from './subscriptionHealth';

export interface DashboardOverview {
  portfolio?: PortfolioSummary;
  market_snapshot?: MarketSnapshot[];
  subscription_health?: SubscriptionHealth;
  recent_decisions?: PromptRecord[];
  recent_alerts?: PriceAlert[];
}
