/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */
import type { AssetInfo } from './assetInfo';

export type GetAssets200 = {
  assets?: AssetInfo[];
  count?: number;
};
