/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */
import type { GetHistoryTimeframe } from './getHistoryTimeframe';

export type GetHistoryParams = {
/**
 * Timeframe for OHLC aggregation
 */
timeframe?: GetHistoryTimeframe;
/**
 * Maximum number of data points to return
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
};
