/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */

export type GetHistoryTimeframe = typeof GetHistoryTimeframe[keyof typeof GetHistoryTimeframe];


export const GetHistoryTimeframe = {
  '1h': '1h',
  '4h': '4h',
  '1d': '1d',
  '1w': '1w',
} as const;
