/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */
import type { GetLogLevel200Level } from './getLogLevel200Level';

export type GetLogLevel200 = {
  level?: GetLogLevel200Level;
};
