/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */
import type { PromptRecord } from './promptRecord';

export type ListPrompts200 = {
  prompts?: PromptRecord[];
  count?: number;
};
