/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */

export interface MarketSnapshot {
  pair?: string;
  bid?: number;
  ask?: number;
  last?: number;
  volume_24h?: number;
  updated_at?: string;
  sparkline?: number[];
}
