/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */
import type { PortfolioSummaryBalances } from './portfolioSummaryBalances';

export interface PortfolioSummary {
  total_value_usd?: number;
  balances?: PortfolioSummaryBalances;
  open_positions?: number;
  updated_at?: string;
}
