/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */

export interface PriceAlert {
  pair?: string;
  change_pct?: number;
  current?: number;
  previous?: number;
  updated_at?: string;
  direction?: string;
}
