/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */

export interface PromptRecord {
  id?: number;
  created_at?: string;
  type?: string;
  pair?: string;
  raw_prompt?: string;
  raw_answer?: string;
  answer?: string;
  action?: string;
  size_pct?: number;
  confidence?: number;
  success?: boolean;
}
