/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */

export type SetLogLevelBodyLevel = typeof SetLogLevelBodyLevel[keyof typeof SetLogLevelBodyLevel];


export const SetLogLevelBodyLevel = {
  trace: 'trace',
  debug: 'debug',
  info: 'info',
  warn: 'warn',
  error: 'error',
} as const;
