/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */

export interface SignalSummary {
  symbol?: string;
  momentum_signal?: string;
  breakout_signal?: string;
  volume_signal?: string;
  updated_at?: string;
}
