/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */

export interface TradeRecord {
  pair?: string;
  action?: string;
  order_type?: string;
  size?: number;
  price?: number;
  cost?: number;
  fee?: number;
  mode?: string;
  reasoning?: string;
  confidence?: number;
  timestamp?: string;
}
