/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */

export interface TradingPair {
  /** Trading pair symbol (e.g., BTCUSD) */
  symbol?: string;
  /** Alternative name (e.g., XBT/USD) */
  altname?: string;
  /** WebSocket pair name (e.g., BTC/USD) */
  ws_name?: string;
}
