/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddSubscription200,
  AddSubscriptionBody,
  GetAssets200,
  GetAssetsParams,
  GetHealth200,
  GetLogLevel200,
  ListPrompts200,
  ListPromptsParams,
  ListSubscriptions200,
  ListSubscriptionsDetail200,
  RemoveSubscription200,
  SetLogLevel200,
  SetLogLevelBody,
  TickerData
} from './models';

export const getKrakenTraderAPI = (axiosInstance: AxiosInstance = axios.default) => {
/**
 * @summary Health check
 */
const getHealth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetHealth200>> => {
    return axiosInstance.get(
      `/health`,options
    );
  }

/**
 * @summary List active subscriptions
 */
const listSubscriptions = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListSubscriptions200>> => {
    return axiosInstance.get(
      `/subscriptions`,options
    );
  }

/**
 * @summary Add a new subscription
 */
const addSubscription = (
    addSubscriptionBody: AddSubscriptionBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AddSubscription200>> => {
    return axiosInstance.post(
      `/subscriptions`,
      addSubscriptionBody,options
    );
  }

/**
 * @summary Remove a subscription
 */
const removeSubscription = (
    symbol: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RemoveSubscription200>> => {
    return axiosInstance.delete(
      `/subscriptions/${symbol}`,options
    );
  }

/**
 * @summary List subscriptions with detail
 */
const listSubscriptionsDetail = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListSubscriptionsDetail200>> => {
    return axiosInstance.get(
      `/subscriptions/detail`,options
    );
  }

/**
 * @summary List recent prompts
 */
const listPrompts = (
    params?: ListPromptsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListPrompts200>> => {
    return axiosInstance.get(
      `/prompts`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Get current log level
 */
const getLogLevel = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetLogLevel200>> => {
    return axiosInstance.get(
      `/loglevel`,options
    );
  }

/**
 * @summary Set console log level
 */
const setLogLevel = (
    setLogLevelBody: SetLogLevelBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SetLogLevel200>> => {
    return axiosInstance.post(
      `/loglevel`,
      setLogLevelBody,options
    );
  }

/**
 * @summary Get tradable assets
 */
const getAssets = (
    params?: GetAssetsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetAssets200>> => {
    return axiosInstance.get(
      `/assets`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Get current ticker for a symbol
 */
const getTicker = (
    symbol: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TickerData>> => {
    return axiosInstance.get(
      `/ticker/${symbol}`,options
    );
  }

return {getHealth,listSubscriptions,addSubscription,removeSubscription,listSubscriptionsDetail,listPrompts,getLogLevel,setLogLevel,getAssets,getTicker}};
export type GetHealthResult = AxiosResponse<GetHealth200>
export type ListSubscriptionsResult = AxiosResponse<ListSubscriptions200>
export type AddSubscriptionResult = AxiosResponse<AddSubscription200>
export type RemoveSubscriptionResult = AxiosResponse<RemoveSubscription200>
export type ListSubscriptionsDetailResult = AxiosResponse<ListSubscriptionsDetail200>
export type ListPromptsResult = AxiosResponse<ListPrompts200>
export type GetLogLevelResult = AxiosResponse<GetLogLevel200>
export type SetLogLevelResult = AxiosResponse<SetLogLevel200>
export type GetAssetsResult = AxiosResponse<GetAssets200>
export type GetTickerResult = AxiosResponse<TickerData>
