/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Kraken Trader API
 * API for managing market data subscriptions and prompts
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddSubscription200,
  AddSubscriptionBody,
  DashboardOverview,
  DeleteSubscription200,
  DeleteSubscriptionBody,
  GetAssets200,
  GetAssetsParams,
  GetHealth200,
  GetHistory200,
  GetHistoryParams,
  GetLogLevel200,
  GetNews200,
  GetPairs200,
  GetSignals200,
  GetTrades200,
  GetTradesParams,
  ListPrompts200,
  ListPromptsParams,
  ListSubscriptions200,
  SetLogLevel200,
  SetLogLevelBody,
  TickerData
} from './models';

export const getKrakenTraderAPI = (axiosInstance: AxiosInstance = axios.default) => {
/**
 * @summary Health check
 */
const getHealth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetHealth200>> => {
    return axiosInstance.get(
      `/health`,options
    );
  }

/**
 * @summary List active subscriptions with full details
 */
const listSubscriptions = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListSubscriptions200>> => {
    return axiosInstance.get(
      `/subscriptions`,options
    );
  }

/**
 * @summary Add a new subscription
 */
const addSubscription = (
    addSubscriptionBody: AddSubscriptionBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AddSubscription200>> => {
    return axiosInstance.post(
      `/subscriptions`,
      addSubscriptionBody,options
    );
  }

/**
 * @summary Remove a subscription
 */
const deleteSubscription = (
    deleteSubscriptionBody: DeleteSubscriptionBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteSubscription200>> => {
    return axiosInstance.post(
      `/subscriptions/delete`,
      deleteSubscriptionBody,options
    );
  }

/**
 * @summary List recent prompts
 */
const listPrompts = (
    params?: ListPromptsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListPrompts200>> => {
    return axiosInstance.get(
      `/prompts`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Get current log level
 */
const getLogLevel = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetLogLevel200>> => {
    return axiosInstance.get(
      `/loglevel`,options
    );
  }

/**
 * @summary Set console log level
 */
const setLogLevel = (
    setLogLevelBody: SetLogLevelBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SetLogLevel200>> => {
    return axiosInstance.post(
      `/loglevel`,
      setLogLevelBody,options
    );
  }

/**
 * @summary Get tradable assets
 */
const getAssets = (
    params?: GetAssetsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetAssets200>> => {
    return axiosInstance.get(
      `/assets`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Get available trading pairs for subscriptions
 */
const getPairs = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetPairs200>> => {
    return axiosInstance.get(
      `/pairs`,options
    );
  }

/**
 * @summary Get current ticker for a symbol
 */
const getTicker = (
    symbol: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TickerData>> => {
    return axiosInstance.get(
      `/ticker/${symbol}`,options
    );
  }

/**
 * @summary Get historical OHLC data for a symbol
 */
const getHistory = (
    symbol: string,
    params?: GetHistoryParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetHistory200>> => {
    return axiosInstance.get(
      `/history/${symbol}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Get consolidated dashboard overview
 */
const getDashboard = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DashboardOverview>> => {
    return axiosInstance.get(
      `/dashboard`,options
    );
  }

/**
 * @summary Get PRISM technical signal summaries
 */
const getSignals = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetSignals200>> => {
    return axiosInstance.get(
      `/signals`,options
    );
  }

/**
 * @summary Get recent news articles
 */
const getNews = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetNews200>> => {
    return axiosInstance.get(
      `/news`,options
    );
  }

/**
 * @summary Get trade execution history
 */
const getTrades = (
    params?: GetTradesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetTrades200>> => {
    return axiosInstance.get(
      `/trades`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

return {getHealth,listSubscriptions,addSubscription,deleteSubscription,listPrompts,getLogLevel,setLogLevel,getAssets,getPairs,getTicker,getHistory,getDashboard,getSignals,getNews,getTrades}};
export type GetHealthResult = AxiosResponse<GetHealth200>
export type ListSubscriptionsResult = AxiosResponse<ListSubscriptions200>
export type AddSubscriptionResult = AxiosResponse<AddSubscription200>
export type DeleteSubscriptionResult = AxiosResponse<DeleteSubscription200>
export type ListPromptsResult = AxiosResponse<ListPrompts200>
export type GetLogLevelResult = AxiosResponse<GetLogLevel200>
export type SetLogLevelResult = AxiosResponse<SetLogLevel200>
export type GetAssetsResult = AxiosResponse<GetAssets200>
export type GetPairsResult = AxiosResponse<GetPairs200>
export type GetTickerResult = AxiosResponse<TickerData>
export type GetHistoryResult = AxiosResponse<GetHistory200>
export type GetDashboardResult = AxiosResponse<DashboardOverview>
export type GetSignalsResult = AxiosResponse<GetSignals200>
export type GetNewsResult = AxiosResponse<GetNews200>
export type GetTradesResult = AxiosResponse<GetTrades200>
