// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for SetLogLevelJSONBodyLevel.
const (
	Debug SetLogLevelJSONBodyLevel = "debug"
	Error SetLogLevelJSONBodyLevel = "error"
	Info  SetLogLevelJSONBodyLevel = "info"
	Trace SetLogLevelJSONBodyLevel = "trace"
	Warn  SetLogLevelJSONBodyLevel = "warn"
)

// Valid indicates whether the value is a known member of the SetLogLevelJSONBodyLevel enum.
func (e SetLogLevelJSONBodyLevel) Valid() bool {
	switch e {
	case Debug:
		return true
	case Error:
		return true
	case Info:
		return true
	case Trace:
		return true
	case Warn:
		return true
	default:
		return false
	}
}

// AssetInfo defines model for AssetInfo.
type AssetInfo struct {
	Aclass          *string  `json:"aclass,omitempty"`
	Altname         *string  `json:"altname,omitempty"`
	CollateralValue *float32 `json:"collateral_value,omitempty"`
	Decimals        *int     `json:"decimals,omitempty"`
	DisplayDecimals *int     `json:"display_decimals,omitempty"`
	MarginRate      *string  `json:"margin_rate,omitempty"`
	Status          *string  `json:"status,omitempty"`
}

// PromptRecord defines model for PromptRecord.
type PromptRecord struct {
	Action     *string    `json:"action,omitempty"`
	Answer     *string    `json:"answer,omitempty"`
	Confidence *float32   `json:"confidence,omitempty"`
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Id         *int       `json:"id,omitempty"`
	Pair       *string    `json:"pair,omitempty"`
	RawAnswer  *string    `json:"raw_answer,omitempty"`
	RawPrompt  *string    `json:"raw_prompt,omitempty"`
	SizePct    *float32   `json:"size_pct,omitempty"`
	Success    *bool      `json:"success,omitempty"`
	Type       *string    `json:"type,omitempty"`
}

// SubscriptionDetail defines model for SubscriptionDetail.
type SubscriptionDetail struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	IsActive  *bool      `json:"is_active,omitempty"`
	LastData  *time.Time `json:"last_data,omitempty"`
	Symbol    *string    `json:"symbol,omitempty"`
}

// TickerData defines model for TickerData.
type TickerData struct {
	Ask       *float32   `json:"ask,omitempty"`
	Bid       *float32   `json:"bid,omitempty"`
	Last      *float32   `json:"last,omitempty"`
	Symbol    *string    `json:"symbol,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Volume    *float32   `json:"volume,omitempty"`
}

// GetAssetsParams defines parameters for GetAssets.
type GetAssetsParams struct {
	EnabledOnly *bool `form:"enabled_only,omitempty" json:"enabled_only,omitempty"`
}

// SetLogLevelJSONBody defines parameters for SetLogLevel.
type SetLogLevelJSONBody struct {
	Level SetLogLevelJSONBodyLevel `json:"level"`
}

// SetLogLevelJSONBodyLevel defines parameters for SetLogLevel.
type SetLogLevelJSONBodyLevel string

// ListPromptsParams defines parameters for ListPrompts.
type ListPromptsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// AddSubscriptionJSONBody defines parameters for AddSubscription.
type AddSubscriptionJSONBody struct {
	Symbol string `json:"symbol"`
}

// SetLogLevelJSONRequestBody defines body for SetLogLevel for application/json ContentType.
type SetLogLevelJSONRequestBody SetLogLevelJSONBody

// AddSubscriptionJSONRequestBody defines body for AddSubscription for application/json ContentType.
type AddSubscriptionJSONRequestBody AddSubscriptionJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get tradable assets
	// (GET /assets)
	GetAssets(c *gin.Context, params GetAssetsParams)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// Get current log level
	// (GET /loglevel)
	GetLogLevel(c *gin.Context)
	// Set console log level
	// (POST /loglevel)
	SetLogLevel(c *gin.Context)
	// List recent prompts
	// (GET /prompts)
	ListPrompts(c *gin.Context, params ListPromptsParams)
	// List active subscriptions
	// (GET /subscriptions)
	ListSubscriptions(c *gin.Context)
	// Add a new subscription
	// (POST /subscriptions)
	AddSubscription(c *gin.Context)
	// List subscriptions with detail
	// (GET /subscriptions/detail)
	ListSubscriptionsDetail(c *gin.Context)
	// Remove a subscription
	// (DELETE /subscriptions/{symbol})
	RemoveSubscription(c *gin.Context, symbol string)
	// Get current ticker for a symbol
	// (GET /ticker/{symbol})
	GetTicker(c *gin.Context, symbol string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAssets operation middleware
func (siw *ServerInterfaceWrapper) GetAssets(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAssetsParams

	// ------------- Optional query parameter "enabled_only" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "enabled_only", c.Request.URL.Query(), &params.EnabledOnly, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter enabled_only: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAssets(c, params)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetLogLevel operation middleware
func (siw *ServerInterfaceWrapper) GetLogLevel(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLogLevel(c)
}

// SetLogLevel operation middleware
func (siw *ServerInterfaceWrapper) SetLogLevel(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetLogLevel(c)
}

// ListPrompts operation middleware
func (siw *ServerInterfaceWrapper) ListPrompts(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPromptsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPrompts(c, params)
}

// ListSubscriptions operation middleware
func (siw *ServerInterfaceWrapper) ListSubscriptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSubscriptions(c)
}

// AddSubscription operation middleware
func (siw *ServerInterfaceWrapper) AddSubscription(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddSubscription(c)
}

// ListSubscriptionsDetail operation middleware
func (siw *ServerInterfaceWrapper) ListSubscriptionsDetail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSubscriptionsDetail(c)
}

// RemoveSubscription operation middleware
func (siw *ServerInterfaceWrapper) RemoveSubscription(c *gin.Context) {

	var err error

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", c.Param("symbol"), &symbol, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter symbol: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveSubscription(c, symbol)
}

// GetTicker operation middleware
func (siw *ServerInterfaceWrapper) GetTicker(c *gin.Context) {

	var err error

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", c.Param("symbol"), &symbol, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter symbol: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTicker(c, symbol)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/assets", wrapper.GetAssets)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/loglevel", wrapper.GetLogLevel)
	router.POST(options.BaseURL+"/loglevel", wrapper.SetLogLevel)
	router.GET(options.BaseURL+"/prompts", wrapper.ListPrompts)
	router.GET(options.BaseURL+"/subscriptions", wrapper.ListSubscriptions)
	router.POST(options.BaseURL+"/subscriptions", wrapper.AddSubscription)
	router.GET(options.BaseURL+"/subscriptions/detail", wrapper.ListSubscriptionsDetail)
	router.DELETE(options.BaseURL+"/subscriptions/:symbol", wrapper.RemoveSubscription)
	router.GET(options.BaseURL+"/ticker/:symbol", wrapper.GetTicker)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYTW/jNhD9KwTboxq7u3upb94N0AZNi2CdnorAGItjmWt+aMmRUzfwfy8oyrFk0aqz",
	"cRctepPFMTl8780bUk88t7q0Bg15PnniPl+hhvpx6j3SjVna8KN0tkRHEushyBX4+om2JfIJ9+SkKfgu",
	"46DIgMbkWG6VAkIHar4BVbWDTKUX6EKQwFxqUO3ZpSEsmlHpSwXb+XCUBldIM3dA6UQ8AVWp/HfZ/o1d",
	"fMKcQvCds7qkj5hbJ1JQkLQmDYXxj+hOIGGWUqDJ0xjkDoFQzIHC8NI6HZ64AMLvSGrkWX9KKdJYlCDT",
	"OTh4nA+kGIbLeutpCOWfOC9zSubvqzzHjkAW1ioEw58BPgv6WbXwuZNlgPgaCaTqE/BFWPl54G2D6QwV",
	"eJoLIDh/Rr/VC6vO3Na9zNforpsFjvTk10lIFx1+D+9DrmkOTmWU8aoUL4ZsY1WlU2rtbzC8ko1vCHwm",
	"kE/49O6GLa1jGgwU0hRMg1sjsYA18y2yPQMjWJSfD+lIUmGJnx2s0bB7BwIdm97d8Ixv0Pk4/fdX46tx",
	"SNaWaKCUfMLfXo2v3vJQBbSq8R1BsLX6scB6/wF9CIveCD7hPyJNY0T4kwONhM7zye9PXIY1Plfotjzj",
	"0eQ4GlgoFHNrVHgb7TNufAmVIj4hV2HWE9nuIeMOfWmNj7y/GY9rNVtDaOq8oCyVzOvMRp989JjD/Meq",
	"2W9KEur64VuHSz7h34wOBj9q3H10sPYDe+AcbKM3VYZSXpJmusvwrfTE7JKRAxGQYU1mu9oVtAa3jSD3",
	"IjJOUASg+S+1KPhD+M9ohaBoNUTXTzHiongeGgT+AbqstWfX/bo4B5KYH8tXmK/ZPscjQNoxLSRmW0+o",
	"GySULRRuUA1hcWuL2zrmomg8L4um0iEvcpAHlxC4qAreVHvGH8EZnnF0zjr+8EVgfaicQ0NM2YLFZfvK",
	"yXsxCcQyXlqfAGl2BNLnCj29t2L7r8An5CMdijBJnPUhCdohLtjL7p9h+zXHpoQz7NliTfsJM76LmXYj",
	"b8wGlBQnNTALGrDGW4XDGghVs+8hp4omGNbdc585w/GV1JLSVv9mnPVN87JGf9KcM97a6VlNoHOu7fWB",
	"l5j9fuUuTfWowzyUaquTNyTtMY8sdXr/IFezTuTXwraX31kIJ46vr8I5nlm7B6UU6Mm4Vn103p+2yqkQ",
	"7dCL2eXhZHporu/vP4x+m13zvzPF5r9f3xVPet+Lzv59btsIMxBiwBffg2ANAzHmh8QJWzkEsd1zvwjT",
	"dQQyFYIBM/jYkceAOnrlORLPN7HzqrSR/v+rVru3mUdJKxauVp5Al8miTfxB7IE7n5unKMZdVIbC+AGk",
	"S9BH1HaDR6Wd6nzh0nRofI3Mj8us3QmP9f/w3ytBV4PTFOG7foH9aoktbWWO6yqCyuAlZUX1d4AOZ6cO",
	"9vGTwaV4Osd3X8vdULG1PoAM3AEiPPXHgYFbQBO1tC6Av997/y652/0VAAD//5qT/XLsFAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
