// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for SetLogLevelJSONBodyLevel.
const (
	Debug SetLogLevelJSONBodyLevel = "debug"
	Error SetLogLevelJSONBodyLevel = "error"
	Info  SetLogLevelJSONBodyLevel = "info"
	Trace SetLogLevelJSONBodyLevel = "trace"
	Warn  SetLogLevelJSONBodyLevel = "warn"
)

// Valid indicates whether the value is a known member of the SetLogLevelJSONBodyLevel enum.
func (e SetLogLevelJSONBodyLevel) Valid() bool {
	switch e {
	case Debug:
		return true
	case Error:
		return true
	case Info:
		return true
	case Trace:
		return true
	case Warn:
		return true
	default:
		return false
	}
}

// AssetInfo defines model for AssetInfo.
type AssetInfo struct {
	Aclass          *string  `json:"aclass,omitempty"`
	Altname         *string  `json:"altname,omitempty"`
	CollateralValue *float32 `json:"collateral_value,omitempty"`
	Decimals        *int     `json:"decimals,omitempty"`
	DisplayDecimals *int     `json:"display_decimals,omitempty"`
	MarginRate      *string  `json:"margin_rate,omitempty"`
	Status          *string  `json:"status,omitempty"`
}

// PromptRecord defines model for PromptRecord.
type PromptRecord struct {
	Action     *string    `json:"action,omitempty"`
	Answer     *string    `json:"answer,omitempty"`
	Confidence *float32   `json:"confidence,omitempty"`
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Id         *int       `json:"id,omitempty"`
	Pair       *string    `json:"pair,omitempty"`
	RawAnswer  *string    `json:"raw_answer,omitempty"`
	RawPrompt  *string    `json:"raw_prompt,omitempty"`
	SizePct    *float32   `json:"size_pct,omitempty"`
	Success    *bool      `json:"success,omitempty"`
	Type       *string    `json:"type,omitempty"`
}

// SubscriptionDetail defines model for SubscriptionDetail.
type SubscriptionDetail struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	IsActive  *bool      `json:"is_active,omitempty"`
	LastData  *time.Time `json:"last_data,omitempty"`
	Symbol    *string    `json:"symbol,omitempty"`
}

// TickerData defines model for TickerData.
type TickerData struct {
	Ask       *float32   `json:"ask,omitempty"`
	Bid       *float32   `json:"bid,omitempty"`
	Last      *float32   `json:"last,omitempty"`
	Symbol    *string    `json:"symbol,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Volume    *float32   `json:"volume,omitempty"`
}

// TradingPair defines model for TradingPair.
type TradingPair struct {
	// Altname Alternative name (e.g., XBT/USD)
	Altname *string `json:"altname,omitempty"`

	// Symbol Trading pair symbol (e.g., BTCUSD)
	Symbol *string `json:"symbol,omitempty"`

	// WsName WebSocket pair name (e.g., BTC/USD)
	WsName *string `json:"ws_name,omitempty"`
}

// GetAssetsParams defines parameters for GetAssets.
type GetAssetsParams struct {
	EnabledOnly *bool `form:"enabled_only,omitempty" json:"enabled_only,omitempty"`
}

// SetLogLevelJSONBody defines parameters for SetLogLevel.
type SetLogLevelJSONBody struct {
	Level SetLogLevelJSONBodyLevel `json:"level"`
}

// SetLogLevelJSONBodyLevel defines parameters for SetLogLevel.
type SetLogLevelJSONBodyLevel string

// ListPromptsParams defines parameters for ListPrompts.
type ListPromptsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// AddSubscriptionJSONBody defines parameters for AddSubscription.
type AddSubscriptionJSONBody struct {
	Symbol string `json:"symbol"`
}

// DeleteSubscriptionJSONBody defines parameters for DeleteSubscription.
type DeleteSubscriptionJSONBody struct {
	Symbol string `json:"symbol"`
}

// SetLogLevelJSONRequestBody defines body for SetLogLevel for application/json ContentType.
type SetLogLevelJSONRequestBody SetLogLevelJSONBody

// AddSubscriptionJSONRequestBody defines body for AddSubscription for application/json ContentType.
type AddSubscriptionJSONRequestBody AddSubscriptionJSONBody

// DeleteSubscriptionJSONRequestBody defines body for DeleteSubscription for application/json ContentType.
type DeleteSubscriptionJSONRequestBody DeleteSubscriptionJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get tradable assets
	// (GET /assets)
	GetAssets(c *gin.Context, params GetAssetsParams)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// Get current log level
	// (GET /loglevel)
	GetLogLevel(c *gin.Context)
	// Set console log level
	// (POST /loglevel)
	SetLogLevel(c *gin.Context)
	// Get available trading pairs for subscriptions
	// (GET /pairs)
	GetPairs(c *gin.Context)
	// List recent prompts
	// (GET /prompts)
	ListPrompts(c *gin.Context, params ListPromptsParams)
	// List active subscriptions
	// (GET /subscriptions)
	ListSubscriptions(c *gin.Context)
	// Add a new subscription
	// (POST /subscriptions)
	AddSubscription(c *gin.Context)
	// Remove a subscription
	// (POST /subscriptions/delete)
	DeleteSubscription(c *gin.Context)
	// List subscriptions with detail
	// (GET /subscriptions/detail)
	ListSubscriptionsDetail(c *gin.Context)
	// Get current ticker for a symbol
	// (GET /ticker/{symbol})
	GetTicker(c *gin.Context, symbol string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAssets operation middleware
func (siw *ServerInterfaceWrapper) GetAssets(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAssetsParams

	// ------------- Optional query parameter "enabled_only" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "enabled_only", c.Request.URL.Query(), &params.EnabledOnly, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter enabled_only: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAssets(c, params)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetLogLevel operation middleware
func (siw *ServerInterfaceWrapper) GetLogLevel(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLogLevel(c)
}

// SetLogLevel operation middleware
func (siw *ServerInterfaceWrapper) SetLogLevel(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetLogLevel(c)
}

// GetPairs operation middleware
func (siw *ServerInterfaceWrapper) GetPairs(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPairs(c)
}

// ListPrompts operation middleware
func (siw *ServerInterfaceWrapper) ListPrompts(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPromptsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPrompts(c, params)
}

// ListSubscriptions operation middleware
func (siw *ServerInterfaceWrapper) ListSubscriptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSubscriptions(c)
}

// AddSubscription operation middleware
func (siw *ServerInterfaceWrapper) AddSubscription(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddSubscription(c)
}

// DeleteSubscription operation middleware
func (siw *ServerInterfaceWrapper) DeleteSubscription(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteSubscription(c)
}

// ListSubscriptionsDetail operation middleware
func (siw *ServerInterfaceWrapper) ListSubscriptionsDetail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSubscriptionsDetail(c)
}

// GetTicker operation middleware
func (siw *ServerInterfaceWrapper) GetTicker(c *gin.Context) {

	var err error

	// ------------- Path parameter "symbol" -------------
	var symbol string

	err = runtime.BindStyledParameterWithOptions("simple", "symbol", c.Param("symbol"), &symbol, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter symbol: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTicker(c, symbol)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/assets", wrapper.GetAssets)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/loglevel", wrapper.GetLogLevel)
	router.POST(options.BaseURL+"/loglevel", wrapper.SetLogLevel)
	router.GET(options.BaseURL+"/pairs", wrapper.GetPairs)
	router.GET(options.BaseURL+"/prompts", wrapper.ListPrompts)
	router.GET(options.BaseURL+"/subscriptions", wrapper.ListSubscriptions)
	router.POST(options.BaseURL+"/subscriptions", wrapper.AddSubscription)
	router.POST(options.BaseURL+"/subscriptions/delete", wrapper.DeleteSubscription)
	router.GET(options.BaseURL+"/subscriptions/detail", wrapper.ListSubscriptionsDetail)
	router.GET(options.BaseURL+"/ticker/:symbol", wrapper.GetTicker)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYW2/jNhP9KwS/76EF1Dh7eanfcgG6QdNFsE7RAkVgjMWxww0vWnLk1A383wuScixZ",
	"tOps0qBA+yZLY3J4zuGZIR94aXVlDRryfPzAfXmLGuLjifdIF2Zuw4/K2QodSYyfoFTg4xOtKuRj7slJ",
	"s+DrgoMiAxqz30qrFBA6UNMlqLodZGo9QxeCBJZSg2qPLg3hovkqfaVgNR2O0uAW0kwdUD4RT0B1Lv91",
	"sXljZ5+xpBB85ayu6BOW1okcFCStyUNh/D26PUiYuRRoyjwGpUMgFFOg8HlunQ5PXADhdyQ18qI/pBR5",
	"LCqQ+Rwc3E8HUgyfq7j0PITyD5xWJWXz93VZYkcgM2sVguGPAB8E/aSe+dLJKkB8jgRS9Qn4Kqz8NPC2",
	"xHyGCjxNBRAcPqJf6ZlVBy7rWpZ36M6bCXb05O+ykM46/G7fh1zzHOzLqOB1JZ4M2dKqWufUml2gAyHN",
	"4qqR3s4Ktw4h8JFePuYnitAZCLywEMG+waPFUcF+Pb0e/Tw5/3YY9+5YTQYsqJ+loM1wp9dn+0a799N8",
	"ar/gbGLLO6Q0YDu70+uzPdn1kQmvZOOoO2u/umBz65gGA4uQuAYXpgsqZL61DTwDI1jamD7MKUmFKX50",
	"cIeGhXWjYydXF7zgS3Q+Df/m6PjoOKzQVmigknzM3x0dH73jwR/oNvIygmD48XGBURmBNQiTXgg+5j8g",
	"naSI8CcHGgmd5+PfHrgMc3yp0a14wROCHA3MFIqpNSq8TYUlLXwOtSI+Jldj0dt+65uCO/SVNT7p5e3x",
	"cdzn1hCamBdUlZJlzGz02Sf33Y6/u582i5KEOj783+Gcj/n/RtvSN2rq3mhb9LbsgXOwSq5dG8q5bJ7p",
	"LsOX0hOzc0YORECGNZmto19qDW6VQO5FFJxgEYDmP0VR8Jvwn9EtgqLbIbo+pIgXxXNbOvF30FXUnr07",
	"VPxdSFJ+rLzF8o5tctwBpB3TQmKy8oS6QULZhcIlqiEsLu3iMsa8KBqP06KpdciLHJTBPwXO6gVvdnvB",
	"78EZXnB0zjp+81VgndXOoSGm7IKlafvKKXsxGcQKXlmfAWmyA9KXGj2dWrH6R+AT8pEORRgkjXqTBW0b",
	"F+xl/few/ZyGMuMMG7ZYU5jDiO9Tpt3IC7MEJcVeDUyCBqzxVuGwBsKuCZVs0O2vYsCLIrjXQVOferhP",
	"tzuMnlM/xY5hCVJFt6VWy5Cz5T2RsWx3KvQ+w94U7X2Qh5SuHgv7ASVWSS0pX1vfHhf9KnXzalxuV3oQ",
	"m50j1rPo3MzcpS9+dVgGb2y1Tg1JG8wTS10qh7ia7JD+Otj28jsI4cxJ6nnbJh6fdnSfAT0b1zKkzvv9",
	"telEiHboi9Wn7fFh2800DT3/qyrU/Pf1y9DeYvOkY2if2zbCDIQYKESnIFjDQIr5PneccwhiteF+Fobr",
	"CORECAbM4H1HHgPq6G3PkUCF6Y4nr5vz+P3VpPPm4uPZh//Ewxxqu3yKfN73Yz5aYnNbm13VfIpjM3iO",
	"aDY3SYdZe+OX/y6D79453Eu6ZSQ1egJdZZ0+8wexAW6IG4qXYaOHpL71UEOa7s329EYVxKNu0xo1Wt7d",
	"S+1e6RDHf27HNNjCbm8BB457CZ54DzRw4GuiQisK7HHt/S50vf4zAAD//zAu16rxFwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
